/**
 * Canonical error codes shared across the platform. Domain-specific codes
 * (e.g. `INVALID_CREDENTIALS`) are registered here too so every thrown error
 * carries a stable, documented code that HTTP clients can switch on.
 */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DEPLOYMENT_ERROR: "DEPLOYMENT_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
  WORKER_ERROR: "WORKER_ERROR",
  NGINX_ERROR: "NGINX_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",

  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  INVALID_CSRF_TOKEN: "INVALID_CSRF_TOKEN",
  FORBIDDEN: "FORBIDDEN",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  INVALID_ROLES: "INVALID_ROLES",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Default HTTP status for each canonical code. Concrete errors may override
 * with a more specific status.
 */
export const HTTP_STATUS_BY_CODE: Readonly<Record<ErrorCode, number>> = {
  VALIDATION_ERROR: 400,
  AUTHENTICATION_ERROR: 401,
  AUTHORIZATION_ERROR: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  PAYLOAD_TOO_LARGE: 413,
  INTERNAL_ERROR: 500,
  DEPLOYMENT_ERROR: 422,
  STORAGE_ERROR: 500,
  WORKER_ERROR: 500,
  NGINX_ERROR: 500,
  DATABASE_ERROR: 500,

  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_DISABLED: 403,
  INVALID_REFRESH_TOKEN: 401,
  MISSING_REFRESH_TOKEN: 400,
  INVALID_CSRF_TOKEN: 403,
  FORBIDDEN: 403,
  WEAK_PASSWORD: 400,
  INVALID_CURRENT_PASSWORD: 400,
  INVALID_ROLES: 400,
  QUOTA_EXCEEDED: 413,
};
